Fix a bug due to Python binary selection by cmake
Bug:
    `$ sudo make install`
    deploys Python related files into the wrong version and installation fails:

Obs:
~~~ extract from installation log
$ sudo make install
(...)
running build
running build_py
copying /home/dim/git/rozofs/manager/rozofs/__init__.py -> build/lib.linux-x86_64-3.5/rozofs
copying /home/dim/git/rozofs/manager/rozofs/core/libconfig.py -> build/lib.linux-x86_64-3.5/rozofs/core
running build_ext
running build_scripts
running install_lib
copying build/lib.linux-x86_64-3.5/rozofs/core/libconfig.py -> /usr/local/lib/python3.5/site-packages/rozofs/core
copying build/lib.linux-x86_64-3.5/rozofs/__init__.py -> /usr/local/lib/python3.5/site-packages/rozofs
byte-compiling /usr/local/lib/python3.5/site-packages/rozofs/cli/volume.py to volume.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/site-packages/rozofs/core/agent.py to agent.cpython-35.pyc
byte-compiling /usr/local/lib/python3.5/site-packages/rozofs/__init__.py to __init__.cpython-35.pyc
running install_scripts
changing mode of /usr/local/bin/rozo to 755
running install_egg_info
Removing /usr/local/lib/python3.5/site-packages/rozofs_manager-1.6._alpha5-py3.5.egg-info
Writing /usr/local/lib/python3.5/site-packages/rozofs_manager-1.6._alpha5-py3.5.egg-info
writing list of installed files to '/home/dim/git/rozofs/build/manager_install_manifest.txt'
  File "/usr/local/lib/python3.5/site-packages/rozofs/cli/volume.py", line 70
    print 'WARNING: %s is not reachable' % str(host)
                                       ^
SyntaxError: invalid syntax

  File "/usr/local/lib/python3.5/site-packages/rozofs/core/agent.py", line 81
    oldmask = os.umask(022)
                         ^
SyntaxError: invalid token
~~~

Problem:
	Here, files are managed by python3.5 since we target `/usr/bin/python`.

Solution:
Thus, PythonInterp is proposed for better determination of the python2.7 or python2.6 executable path.